# model
model_name_or_path: /data1/huggingface/Qwen2.5-3B-Instruct
model_revision: main
resume_from_checkpoint: true
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: model_weights/tbdel # oscillation

# dataset
dataset_id_or_path: datasets/posterior/train_posterior.parquet

# Swanlab
swanlab: false 
workspace: Youxiang
project: Reward-oscillation
experiment_name: test-2048-clipratio
report_to: none

# Training parameters
max_steps: 3000
num_train_epochs: 5
per_device_train_batch_size: 2
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-6 # changed this from 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03 
seed: 2025 

# GRPO 
beta: 0.001 # KL penalty factor
max_prompt_length: 1024 
max_completion_length: 2048 
# num_generations controls the averaging process of reward computation
# final_num_gen = num_generations*per_device_train_batch_size*num_gpus
num_generations: 8 
temperature: 0.6  # This controls the exploration
use_vllm: true 
vllm_device: cuda:2
vllm_gpu_memory_utilization: 0.6

# Logging arguments
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_steps: 500 
save_total_limit: 4 

# # Lora arguments
# use_peft: true
# lora_r: 32
# lora_target_modules: ['q_proj', 'v_proj']
# lora_task_type: "CAUSAL_LM"
# # load_in_8bit: true 