# model
model_name_or_path: /data1/huggingface/Qwen2.5-3B-Instruct
model_revision: main
resume_from_checkpoint: true
torch_dtype: bfloat16
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: model_weights/qwen3B-ks-2048-1.1

# dataset
dataset_id_or_path: datasets/posterior/train_posterior.parquet

# Swanlab
swanlab: true 
workspace: Youxiang
project: RiskReasoner-grpo
experiment_name: qwen3B-ks-2048-1.1
report_to: none

# Training parameters
max_steps: 2000
num_train_epochs: 3
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-6 # changed this from 5.0e-7
lr_scheduler_type: cosine
warmup_ratio: 0.03 
seed: 2025 

# GRPO 
beta: 0.001 # KL penalty factor
max_prompt_length: 2048 
max_completion_length: 2048 
# num_generations controls the averaging process of reward computation
# final_num_gen = num_generations*per_device_train_batch_size*num_gpus
num_generations: 10 
temperature: 0.9  # This controls the exploration
use_vllm: true 
vllm_device: cuda:6
vllm_gpu_memory_utilization: 0.6

# Logging arguments
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_steps: 500 
save_total_limit: 5 