# 模型参数
model_name_or_path: /data1/huggingface/DeepSeek-R1-Distill-Llama-8B # Qwen2.5-3B-Instruct
model_revision: main
torch_dtype: bfloat16
lora_r: 16
lora_alpha: 32
attn_implementation: flash_attention_2
bf16: true
tf32: true
output_dir: model_weights/grpo-unsloth-test

# dataset
dataset_id_or_path: datasets/posterior/train_posterior.parquet

# Swanlab
swanlab: true
workspace: Youxiang
project: RiskReasoner-grpo-unsloth
experiment_name: llama-4096
report_to: none

# Training parameters
max_steps: 2000
per_device_train_batch_size: 16
gradient_accumulation_steps: 2
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1e-4 
lr_scheduler_type: cosine 
warmup_ratio: 0.03 
seed: 2025 

# GRPO 
beta: 0.001 
optim: adamw_8bit # 优化器, 8bit加速
max_prompt_length: 2048 
max_completion_length: 4096 
num_generations: 8
use_vllm: true 
vllm_gpu_memory_utilization: 0.6

# Logging arguments
logging_strategy: steps
logging_steps: 1
save_strategy: "steps"
save_steps: 500 
